### PR TITLE
Add OHLC struct

### PR DESCRIPTION
**Pull request by alexandrestein**
Hi,

I started by updating the _KrakenApi_ to _KrakenAPI_ because of GoLinter comments. (important but not significative)
The problem is the compatibility with previous code. It's may be preferable to let this as is.

The main update is the new function of ***KrakenAPI** to get the OHLC as a structured object.

### CODE REVIEW

**Comment by backnight** [comment]
Could it be merged? Needed! If there is incompatibility, is it possible to tag a first version of this repository? So we can correctly import a specific version in our projects without checking out master and risking to break anything. It's a financial library and we need stability/reliability on it.

Thanks for the work.

**Comment by Atsman** [comment]
@beldur why not to merge it?

**Comment by beldur** [comment]
@Atsman Branch needs rebase

**Comment by beldur** [comment]
Done with #52

**Pull request closed without merging**
