### PR TITLE
Add all currency from api

### PR DESCRIPTION
**Pull request by Piega**

### CODE REVIEW

**Comment by Piega** [comment]
Added XLM DAH GNO and all AssetInfo

**Comment by Piega** [comment]
All actual currency added

**Comment by beldur** [comment]
Thanks for your contribution!

Do you know why some Assets like XLTCZCAD have been removed?

**Comment by Piega** [comment]
I don't know but 

https://bitinfocharts.com/markets/kraken/ltc-cad-all.html

it's true!

**Comment by beldur** [comment]
OK!

Thanks a lot :smiley:

**Pull request merged**
