### PR TITLE
Handling and retrying common errors

### PR DESCRIPTION
**Pull request by jonatrey**
- Catching errors 500 and retrying (cloudflare, SSL handshake failure, server error, ...)
- Better handling of errors, retrying on failures involving service overload on Kraken.

### CODE REVIEW

**Comment by beldur** [comment]
Hi, thanks for your Pull Request.

I'm not sure if retry logic should be part of this library. Is it still urgent? As of now, Kraken updated their engine that should result in much less timeouts/server errors etc.

**Comment by jonatrey** [comment]
Hello,

I think the retry should be part of the library as doing it for every call would add a lot of unnecessary code. For instance the Google cloud sdk has that part of the lib (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/e5cd8d099254a84b26ec9e42cbb807553d3823b3/internal/retry.go) 

It's indeed less relevant now that the API is more stable, in practice (polling every minute for a couple of days), I still see the retry being useful.

**Comment by frranck** [comment]
Is this getting merged ?

**Comment by Glavic** [comment]
> 
> 
> Is this getting merged ?

Probably not. I agree with beldur.
Retry could be part of code, but not as default logic...

**Comment by beldur** [comment]
Again thanks for your effort @jonatrey, but I feel this functionality does not belong into the library.

**Pull request closed without merging**
